name: Auto Update Superenalotto

on:
  workflow_dispatch:
  schedule:
    # Se vuoi le 11:00 italiane, imposta 9:00 UTC
    - cron: '27 5 * * *'
    # Se vuoi le 23:00 italiane, imposta 21:00 UTC
    - cron: '0 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 cloudscraper

      - name: Run update script
        run: python update_data.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          # Controlla se ci sono modifiche prima di fare commit
          if [[ -n $(git status --porcelain) ]]; then
            git add storico_completo.csv
            git commit -m "Aggiornamento automatico estrazione"
            git push origin main
          else
            echo "Nessuna modifica da salvare."
          fi